#ifndef __CANIS_H
#define __CANIS_H

#include "Common.h"

#include "AssimpLoader.h"
#include "Camera.h"
#include "CSXLoader.h"
#include "DIFLoader.h"
#include "DXSLoader.h"
#include "DynamicLibrary.h"
#include "Engine.h"
#include "EntityManager.h"
#include "FramebufferObject.h"
#include "GlShader.h"
#include "GlShaderManager.h"
#include "IEntity.h"
#include "IEntityFactory.h"
#include "IObject.h"
#include "IPlugin.h"
#include "Light.h"
#include "LW14Loader.h"
#include "Material.h"
#include "MaterialLoader.h"
#include "MaterialManager.h"
#include "Mesh.h"
#include "MeshManager.h"
#include "PluginManager.h"
#include "ProgramLoader.h"
#include "Prop.h"
#include "PropFactory.h"
#include "Scene.h"
#include "SceneLoader.h"
#include "SceneNode.h"
#include "SceneWriter.h"
#include "Script.h"
#include "ScriptManager.h"
#include "StaticMesh.h"
#include "StaticMeshFactory.h"
#include "Renderer.h"
#include "RenderManager.h"
#include "RenderTarget.h"
#include "SkyBox.h"
#include "Texture.h"
#include "TextureManager.h"
#include "VertexObject.h"

#endif
